title: Brume
description: ""
baseurl: ""
url: "https://maviawa.github.io"
author: Margot

theme: null
plugins:
  - jekyll-feed

collections:
  writing:
    output: true
    permalink: /writing/:name/
  films:
    output: true
    permalink: /films/:name/
  fragments:
    output: true
    permalink: /fragments/:name/
  albums:
    output: true
    permalink: /albums/:name/

defaults:
  - scope:
      path: ""
      type: writing
    values:
      layout: piece
  - scope:
      path: ""
      type: films
    values:
      layout: film
  - scope:
      path: ""
      type: fragments
    values:
      layout: piece
  - scope:
      path: ""
      type: albums
    values:
      layout: album
